source 'https://github.com/CocoaPods/Specs.git'

target 'LECropPictureViewController', :exclusive => true do
  pod "LECropPictureViewController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "LECropPictureViewController", :path => "../"

  
end
